vich_uploader:
    db_driver: orm


    mappings:
        image_serie:
            uri_prefix: /images/series
            upload_destination: '%kernel.project_dir%/public/images/series'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
